name: aad_oauth
description: A Flutter OAuth package for performing user authentication against Azure Active Directory OAuth2 v2.0 endpoint.
version: 1.0.0
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_webview_plugin: #^0.3.0+2
    git: git@github.com:ktnishide/flutter_webview_plugin.git #git@github.com:fonibo/flutter_webview_plugin.git
  flutter_secure_storage: ^4.2.0
  http: ^0.13.0
  shared_preferences: ^2.0.5
  flutter:
    sdk: flutter
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

publish_to: none